### ISSUE TITLE
Product Transfer Tracking

### ISSUE THREAD

**Issue by CamLee27** [CamLee27/System_Analysis_Project#13]
A system that tracks the movement of the products.

Checklist:

- [ ] Implement a stock product transfer system for relocating products to different locations.
- [ ] Check for accurate tracing of stock movements and adjustments.
- [ ] Create user-friendly page for tracking the products.

Acceptance Criteria: The system is able to accurately track products that are relocated to different locations quickly and efficiently.

Estimated Time: 4 Weeks
