### ISSUE TITLE
Real-Time Tracking

### ISSUE THREAD

**Issue by CamLee27** [CamLee27/System_Analysis_Project#9]
Implement real-time tracking

- [ ] Create user interface for customers to track their shipments using tracking numbers
- [ ]  Create tracking system that monitors the location of the shipments
- [ ] Make sure that the tracking system provides real-time updates

Customers should be able to accurately track their shipments in real-time using the website by entering tracking numbers.
